"""Mise a jour de la table media

Revision ID: 862dcda9dee7
Revises: 
Create Date: 2024-10-04 22:38:02.863167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862dcda9dee7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('titre',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('titre',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
